#!/bin/bash

SOURCE=$1

LIST_FILE=/tmp/list$RANDOM.txt
EXT=.h264.mkv

ARRAY=()
DEG="*C"  #"\0260C"



function thermal_protection
{
   # Thermal protection
   TEMP=$(cat /sys/class/thermal/thermal_zone0/temp)

   echo -e "# CURRENT TEMPERATURE: "$(($TEMP/1000)) $DEG
   while [ $TEMP -gt 64999 ]; do
      sleep 60
      echo -e "# CURRENT TEMPERATURE: "$(($TEMP/1000)) $DEG
   done
   echo ""
}


function select_compression
{
   PS3="# Select compression level: "
   options=("high 4.1 - 18" "high 4.1 - 21" "high 4.1 - 23" "high 4.1 - 26" "high 4.1 - 28" "Quit")
   select opt in "${options[@]}"
   do
      case $opt in
         "high 4.1 - 18")
            echo " -profile:v high -level 4.1 -crf 18 "
            break
            ;;
         "high 4.1 - 21")
            echo " -profile:v high -level 4.1 -crf 21 "
            break
            ;;
         "high 4.1 - 23")
            echo " -profile:v high -level 4.1 -crf 23 "
            break
            ;;
         "high 4.1 - 26")
            echo " -profile:v high -level 4.1 -crf 26 "
            break
            ;;
         "high 4.1 - 28")
            echo " -profile:v high -level 4.1 -crf 28 "
            break
            ;;
         "Quit")
            echo "666"
            break
            ;;
         *) ;;
       esac
   done
}





# Check source
if [[ -d $SOURCE ]]; then

   SOURCE_PATH=$(cd ${SOURCE}; pwd)
   SOURCE_BASE=$(basename $SOURCE_PATH)

   DEST=$SOURCE_PATH"/../"$SOURCE_BASE"-h264"
   mkdir -p $DEST
   DEST_PATH=$(cd ${DEST}; pwd)

   find $SOURCE_PATH -maxdepth 1 -type f -print | sort > $LIST_FILE

   echo "# Source       $SOURCE_PATH"
   echo "# Destination  $DEST_PATH"
   echo ""
   echo "# File in $SOURCE_BASE:"
   cat $LIST_FILE
   echo ""
   echo ""

   # List of files
   while read -r line
   do
      ARRAY+=($line)
   done < "$LIST_FILE"
   TLEN=${#ARRAY[@]}

   rm -r $LIST_FILE

elif [[ -f $SOURCE ]]; then
   echo "# Single input file: $SOURCE"

   ARRAY+=$(readlink -e $SOURCE)
   TLEN=1

   DEST_PATH=$(cd $(dirname $SOURCE) && pwd)

else
   echo "# FATAL: argument is not valid: '$1'."
   exit 1
fi




# Select compress option
COMPRESSION=$(select_compression)

if [ "$COMPRESSION" -eq 666 ]; then
   echo "# Bye."
   exit
fi


echo "# Compression level: " $COMPRESSION
echo ""
echo ""



# Convert!!!!
for (( i=0; i<$TLEN; i++ ));
do
   FILE_PATH=${ARRAY[$i]}
   FILE=$(basename $FILE_PATH)
   FILE_EXT="${FILE##*.}"
   FILE_NAME="${FILE%.*}"

   SOURCE_FILE=$FILE_PATH
   DEST_FILE=$DEST_PATH"/"$FILE_NAME$EXT
   rm -f $DEST_FILE

   echo " in "$SOURCE_FILE
   echo "out "$DEST_FILE
   echo ""


   set -o xtrace

   ####
   ffmpeg -i $SOURCE_FILE -threads 0 -pass 1 -map 0 -c copy  -c:v libx264 -preset veryslow $COMPRESSION  -an       -f matroska  -y /dev/null && \
   ffmpeg -i $SOURCE_FILE -threads 0 -pass 2 -map 0 -c copy  -c:v libx264 -preset veryslow $COMPRESSION  -c:a ac3  -f matroska  -y $DEST_FILE
   ####

   set +o xtrace

   # -filter:v scale=720:-1


   thermal_protection

done
